# not for production usage
# infrastructure such as mysql
version: '3.9'

volumes:
    dev-datavolume:
      driver: local
    
services:
  mysql:
    container_name: dev_mysql

    image: mysql:8.0.33

    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always

    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3

    networks:
      - backend


    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%' # allow root login from any host
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - dev-datavolume:/var/lib/mysql
      - ./dev_mysql.cnf:/etc/mysql/my.cnf

    
networks:
  backend:
    name: backend_network

