# not for production usage
# infrastructure such as mysql
version: '3.9'

volumes:
    dev-datavolume:
      driver: local
    
services:
  mysql:
    container_name: dev_mysql

    image: mysql:8.0.33

    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always

    ports:
      - 3306:3306

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3

    networks:
      - backend

    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%' 
      MYSQL_ROOT_USER: 'root'


    volumes:
      - dev-datavolume:/var/lib/mysql
      - ./dev_mysql.cnf:/etc/mysql/my.cnf

    
networks:
  backend:
    name: backend_network

